import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react-swc';
import fg from 'fast-glob';
import { dirname, resolve } from 'path';
import preserveDirectives from 'rollup-preserve-directives';
import { fileURLToPath } from 'url';
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';
import svgr from 'vite-plugin-svgr';

// Define __dirname for ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// https://vite.dev/config/
export default defineConfig({
  build: {
    lib: {
      // Use an object for entry to clearly define output filenames
      entry: {
        index: resolve(__dirname, './src/index.ts'),
        // Fix: Use a relative glob pattern with forward slashes.
        // fast-glob does not work with Windows backslashes generated by path.resolve()
        ...Object.fromEntries(
          fg
            .sync('src/components/**/*.{ts,tsx}', {
              cwd: __dirname,
              ignore: ['**/*.stories.tsx', '**/*.test.tsx', '**/*.d.ts'], // Good practice to exclude non-source files
            })
            .map(file => {
              // Generate a name from the file name (e.g. "button" from "src/components/button/button.tsx")
              // This ensures dist/button.js is created, matching your package.json exports
              const name =
                file
                  .split('/')
                  .pop()
                  ?.replace(/\.(ts|tsx)$/, '') || 'unknown';
              return [name, resolve(__dirname, file)];
            }),
        ),
      },
      name: 'react-components',
      fileName: (format, entryName) => (format == 'es' ? `${entryName}.js` : `${entryName}.${format}.js`),
      cssFileName: 'index',
      formats: ['es'],
    },
    rollupOptions: {
      external: [
        'react',
        'react-dom',
        'react/jsx-runtime',
        '@fortawesome/fontawesome-svg-core',
        '@fortawesome/react-fontawesome',
        'tailwindcss',
        'tailwind-merge',
        'tailwind-variants',
        '@headlessui/react',
        '@headlessui/tailwindcss',
        'react-animate-height',
      ],
    },
    minify: process.env.NODE_ENV === 'production' ? 'esbuild' : false,
    sourcemap: process.env.NODE_ENV !== 'production',
    emptyOutDir: true,
  },
  plugins: [
    react(),
    dts({ tsconfigPath: './tsconfig.json', insertTypesEntry: true, exclude: 'vite.config.ts' }) as any,
    tailwindcss(),
    preserveDirectives(),
    svgr(),
  ],
});
